### ISSUE TITLE
Defer Offscreen images

### ISSUE THREAD

**Issue by radobotev** [shinsenter/defer-wordpress#64]
Seems like lazy load has stopped working, Pagespeed insights is now showing defer offscreen images even though Lazy Loading is on for images, iframes and videos?

It was working all good before the last update today.

**Comment by radobotev** [comment]
Could you check and update please?

**Comment by shinsenter** [comment]
Hi @ps2master 

Thank you for reaching out with another issue related to my plugin. Could I have more detailed information (such as a screencast or images) of the problem you are experiencing?

**Comment by radobotev** [comment]
Hey, the plugin was working fine until that JSON error you had to fix in the previous version.

![IMG_9649](https://github.com/shinsenter/defer-wordpress/assets/145396576/993396db-f4ce-4fa9-8cb8-bcf7587d1f3f)

The problem I have now is that the plugin doesn’t defer off screen images anymore, like lazy load is completely not working. If I revert to the previous version it works fine, but as then the JSON error is still there. I have had to reset the settings a few times but the issue still occurs. Lazy load images is on as well, but it doesn’t lazy load my images anymore.

**Comment by shinsenter** [comment]
@ps2master 
That's really strange, because I haven't even made many modifications to the core of this plugin.

I would be very happy if you could provide me with the URL to the website you're having issues with, or use the following website to measure the performance of your website, and then give me the URL to its result page.
https://www.webpagetest.org

Thank you.

**Comment by radobotev** [comment]
https://mrsorted.co.uk

https://www.webpagetest.org/result/230922_AiDcV0_78G/

**Comment by shinsenter** [comment]
@ps2master 
Upon [a quick inspection](https://www.webpagetest.org/vitals.php?test=230922_AiDcD5_7BA&run=1), it appears that the plugin is not activated on your website, and the images are being loaded all at once without utilizing lazy loading.

<img width="1035" alt="Screenshot 2023-09-22 at 17 44 25" src="https://github.com/shinsenter/defer-wordpress/assets/2082119/88f9b57f-7986-49f9-ad79-b30c4bfebd77">

It's quite challenging for me to pinpoint the exact reasons in this scenario.

**Comment by shinsenter** [comment]
@ps2master 

By the way, based on the content in the HTML source code, it seems that your website has two other plugins, WP Rocket and Jetpack, interfering with the image lazy loading mechanism.

```
<img width="740" height="740" src="https://mrsorted.co.uk/wp-content/uploads/2023/09/21-09-23-TC_FD7855-001_1_1-740x740.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail jetpack-lazy-image jetpack-lazy-image--handled" alt="Nike x A-Cold-Wall* Air Max Plus 'Onyx'" decoding="async" srcset="https://mrsorted.co.uk/wp-content/uploads/2023/09/21-09-23-TC_FD7855-001_1_1-740x740.jpg 740w, https://mrsorted.co.uk/wp-content/uploads/2023/09/21-09-23-TC_FD7855-001_1_1-700x700.jpg 700w, https://mrsorted.co.uk/wp-content/uploads/2023/09/21-09-23-TC_FD7855-001_1_1-500x500.jpg 500w, https://mrsorted.co.uk/wp-content/uploads/2023/09/21-09-23-TC_FD7855-001_1_1-768x768.jpg 768w, https://mrsorted.co.uk/wp-content/uploads/2023/09/21-09-23-TC_FD7855-001_1_1-900x900.jpg 900w, https://mrsorted.co.uk/wp-content/uploads/2023/09/21-09-23-TC_FD7855-001_1_1-450x450.jpg 450w, https://mrsorted.co.uk/wp-content/uploads/2023/09/21-09-23-TC_FD7855-001_1_1-840x840.jpg 840w, https://mrsorted.co.uk/wp-content/uploads/2023/09/21-09-23-TC_FD7855-001_1_1-540x540.jpg 540w, https://mrsorted.co.uk/wp-content/uploads/2023/09/21-09-23-TC_FD7855-001_1_1-165x165.jpg 165w, https://mrsorted.co.uk/wp-content/uploads/2023/09/21-09-23-TC_FD7855-001_1_1.jpg 1000w" data-lazy-loaded="1" sizes="(max-width: 740px) 100vw, 740px" loading="eager">
```

```
<!-- This website is like a Rocket, isn't it? Performance optimized by WP Rocket. Learn more: https://wp-rocket.me - Debug: cached@1695371701 -->
```

Probably some optimization features of these two plugins may have overridden the DOM structure, making it difficult for my plugin to operate effectively.

**Comment by radobotev** [comment]
I deactivated jetpack and wp rocket, your plugin is on, can you recheck please?

**Comment by shinsenter** [comment]
@ps2master 
Hmm, I don't see any changes in the HTML source code. It seems like your website is still serving a cached version to users, doesn't it?

**Comment by radobotev** [comment]
Just purged all cache from the server

**Comment by shinsenter** [comment]
@ps2master 
https://www.webpagetest.org/vitals.php?test=230922_BiDc38_7MF&run=1
Although the website takes quite some time to load (mostly due to slow server responses when fetching the HTML of the web page and some third-party widgets), the number of image requests has significantly decreased.

I think this time lazy loading has worked perfectly.
![Screen Recording 2023-09-22 at 18 03 20](https://github.com/shinsenter/defer-wordpress/assets/2082119/deba1876-dea8-4248-9ef8-9a4ad96b724a)

**Comment by radobotev** [comment]
![IMG_9653](https://github.com/shinsenter/defer-wordpress/assets/145396576/f68ec708-6974-49c0-823d-0f3a4d65f04e)

defer offscreen images still showing

**Comment by shinsenter** [comment]
@ps2master 
<img width="1174" alt="Screenshot 2023-09-22 at 18 13 16" src="https://github.com/shinsenter/defer-wordpress/assets/2082119/13803fcb-4665-4298-8fd3-039d34f41e9d">

It's OK in my test.
https://pagespeed.web.dev/analysis/https-mrsorted-co-uk/k6783kwa5i?hl=en&form_factor=mobile

Or, Google has scanned a cached version of your website, hasn't it?

Therefore, I believe the issue could be a result of using multiple optimization plugins concurrently, which can sometimes lead to unexpected outcomes. Additionally, occasional server caching may cause delays in reflecting changes when toggling my plugin, giving the impression that it's not working correctly.

**Comment by shinsenter** [comment]
@ps2master 

<img width="927" alt="Screenshot 2023-09-22 at 18 24 41" src="https://github.com/shinsenter/defer-wordpress/assets/2082119/ffaaca4d-1a63-4c01-a62c-45179d3a65c5">

Congratulations on achieving a 100% score in the Best Practices section of the Pagespeed Test. Additionally, it appears that your website is facing several other site performance issues, which I believe are not a result of my plugin.

Because I have been able to check the status of your website and confirm through various measurement tools that the plugin is working perfectly, I will go ahead and close this issue.
